version: "3"

services:
    mitomcat:
        container_name: mitomcat
        #image: docker.io/bitnami/tomcat:10
        image: mitomcat:v1.0 # LA hemos generador desde Dockerfile
               #image-registry.openshift-image-registry.svc:5000/java-ivan/mitomcat:latest
        ports:
          - '8080:8080'
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
#        volumes:
#          - '/home/ubuntu/environment/datos/tomcat/app:/app'
#        environment:
#          - TOMCAT_USERNAME=admin
#          - TOMCAT_PASSWORD=password
#          - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1

# sudo apt install docker-compose -y

# mkdir -p /home/ubuntu/environment/datos/tomcat/app
# chmod 777 -R /home/ubuntu/environment/datos

# docker-compose up

